name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  release:
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Validates Go releaser config
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: check

    - name: Create release on Github
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
